In [2]:
import numpy as np
from utils import *
from algorithms import *
import os

def main():
    input_folder = "input"
    output_folder = "output"
    os.makedirs(output_folder, exist_ok=True)

    input_file = os.path.join(input_folder, "input.txt")

    m, n, preferences, conflicts = read_input(input_file)
    A, B = create_matrix(m, n, preferences, conflicts)
    result_greedy, load_greedy = greedy_algorithm(A, B)
    result_hill, load_hill = hill_climbing(A, B)
    result_back, load_back = backtracking_algorithm(A, B)

    print(f"Greedy algorithm result:\n{result_greedy}\nMax load: {load_greedy}")
    print(f"Hill climbing algorithm result:\n{result_hill}\nMax load: {load_hill}")
    print(f"Backtracking algorithm result:\n{result_back}\nMax load: {load_back}")

    # Write output files
    write_output(result_greedy, os.path.join(output_folder, 'output_greedy.txt'))
    write_output(result_hill, os.path.join(output_folder, 'output_hill.txt'))
    write_output(result_back, os.path.join(output_folder, 'output_back.txt'))

if __name__ == "__main__":
    main()


Greedy algorithm result:
[[1 0 0 0 1 1 0 0 0 1]
 [0 0 0 1 0 0 0 1 0 0]
 [0 1 1 0 0 0 1 0 1 0]]
Max load: 4
Hill climbing algorithm result:
[[1 0 0 0 0 0 1 0 0 1]
 [0 0 0 1 1 0 0 1 0 0]
 [0 1 1 0 0 0 0 0 1 0]]
Max load: 3
Backtracking algorithm result:
[[1 0 0 0 1 1 1 1 0 1]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 1 0]]
Max load: 6
